# Generated with ChatGPT
PHENOTYPE_JSON_FILE_DESCRIPTIONS = {
    "laryngealDystonia.json": "Measures symptoms and characteristics of laryngeal dystonia.",
    "demographics.json": "Measures participant background details.",
    "adhd.json": "Measures attention-related behaviors and symptoms.",
    "airwaystenosis.json": "Measures the severity and characteristics of airway stenosis.",
    "als.json": "Measures symptoms and progression of ALS.",
    "alzheimers.json": "Measures cognitive decline and related symptoms.",
    "benignLesion.json": "Measures features of benign lesions.",
    "bipolar.json": "Measures symptoms and behaviors related to bipolar disorder.",
    "confounders.json": "Measures variables that could impact study outcomes.",
    "customAffectScale.json": "Measures emotional states.",
    "depression.json": "Measures severity and impact of depressive symptoms.",
    "dsm5.json": "Measures criteria according to DSM-5 standards.",
    "dyspnea.json": "Measures the presence and severity of dyspnea.",
    "eligibility.json": "Measures participant eligibility for the study.",
    "enrollment.json": "Measures participant registration details.",
    "gad7.json": "Measures severity of generalized anxiety.",
    "glotticinsufficiency.json": "Measures the characteristics of glottic insufficiency.",
    "laryngealCancer.json": "Measures characteristics of laryngeal cancer.",
    "leicester.json": "Measures specific health or psychological attributes.",
    "panas.json": "Measures positive and negative affect.",
    "huntingtons.json": "Measures the symptoms and progression of Huntington's disease.",
    "parkinsons.json": "Measures symptoms and progression of Parkinson's disease.",
    "participant.json": "Measures general study-related information.",
    "phq9.json": "Measures severity of depressive symptoms.",
    "precancerousLesions.json": "Measures features of precancerous lesions.",
    "ptsd.json": "Measures trauma-related symptoms.",
    "random.json": "Measures variables for various study purposes.",
    "stroop.json": "Measures cognitive control and processing speed.",
    "vhi10.json": "Measures perceived impact of voice disorders.",
    "vocab.json": "Measures language and word knowledge.",
    "vocalFoldParalysis.json": "Measures characteristics of vocal fold paralysis.",
    "voicePerception.json": "Measures how participants perceive voice quality.",
    "voiceSeverity.json": "Measures the impact and seriousness of voice disorders.",
    "winograd.json": "Measures language comprehension and reasoning.",
    "medical_conditions.json": "Measures medical conditions for kids.",
    "pedsvhi10.json": "Measures perceived impact of voice disorders for kids.",
    "peds_voice_outcome_survey.json": "Measures voice outcome for kids.",
    "peds_voice_related_qol.json": "Measures voice quality of life for kids.",
    "phqa.json": "Measures severity of depressive symptoms for kids",
    "q_generic_demographics.json": "Measures participant background details for kids.",
    "subjectparticipant_basic_information.json": "Gets basic information for kids",
    "subjectparticipant_contact_information.json": "Gets Age for kids",
    "q_mood_participant_history.json": "Gets Participant history for Mood protocol",
    "chronicCough.json": "Measures un-explained cough",
    "muscleTension.json": "Measures muscle tension",
    "laryngitis.json" : "Measures laryngitis",
    "anxiety.json": "Measures anxiety"
}
